export const authConstants = {
  //SIGN UP ACTIONS

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  //SIGN UP ACTIONS

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  //SIGN UP ACTIONS

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  // STUDENT OPERATIONS SIGN UPS

  ADD_STUDENT: "ADD_STUDENT",
  ADD_STUDENT_SUCCESS: "ADD_STUDENT_SUCCESS",
  ADD_STUDENT_FAILURE: "ADD_STUDENT_FAILURE",
};

export const feeConstants = {
  //Add Fee

  ADD_FEE_REQUEST: "ADD_FEE_REQUEST",
  ADD_FEE_SUCCESS: "ADD_FEE_SUCCESS",
  ADD_FEE_FAILURE: "ADD_FEE_FAILURE",

  //Update Fee
  UPDATE_FEE_REQUEST: "UPDATE_FEE_REQUEST",
  UPDATE_FEE_SUCCESS: "UPDATE_FEE_SUCCESS",
  UPDATE_FEE_FAILURE: "UPDATE_FEE_FAILURE",
};

export const studentsConstants = {
  VIEW_STUDENT_REQUEST: "VIEW_STUDENT_REQUEST",
  VIEW_STUDENT_SUCCESS: "VIEW_STUDENT_SUCCESS",
  VIEW_STUDENT_FAILRURE: "VIEW_STUDENT_FAILRURE",
};
