export const paymentLogConstants = {
  UV_LOG_REQUEST: "UV_LOG_REQUEST",
  UV_LOG_SUCCESS: "UV_LOG_SUCCESS",
  UV_LOGIN_FAILURE: "UV_LOGIN_FAILURE",

  V_LOG_REQUEST: "V_LOG_REQUEST",
  V_LOG_SUCCESS: "V_LOG_SUCCESS",
  V_LOGIN_FAILURE: "V_LOGIN_FAILURE",

  VERIFY_LOG_REQUEST: "VERIFY_LOG_REQUEST",
  VERIFY_LOG_SUCCESS: "VERIFY_LOG_SUCCESS",
  VERIFY_LOG_FAILURE: "VERIFY_LOG_FAILURE",
};
